# Generated by Django 6.0.7 on 2026-07-28 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='inventory.empresa')),
            ],
            options={
                'verbose_name_plural': 'Atributos',
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='OpcionAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='inventory.atributo')),
            ],
            options={
                'verbose_name_plural': 'Opciones de Atributos',
                'ordering': ['atributo', 'valor'],
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='opciones',
            field=models.ManyToManyField(blank=True, related_name='productos', to='inventory.opcionatributo'),
        ),
    ]
